// Table column labels for use in forms and tables
export const TABLE_COLUMNS = {
    DEFECT_STATE: 'Стан дефекту',
    NUMBER: 'Номер',
    SUBSTATION_REGION: 'РЕМ',
    CREATED_AT: 'Дата реєстрації',
    OBJECT: "Тип об'єкт",
    SUBSTATION: 'Об’єкту',
    PLACE_OF_DEFECT: 'Місце дефекту',
    CONNECTION: "Приєднання",
    ESSENCE_OF_DEFECT: 'Суть дефекту',
    AUTHOR: 'Автор повідомлення',
    RESPONSIBLE_FOR_ELIMINATION: 'Відповідальний за усунення',
    TIME_OF_ELIMINATION: 'Час усунення',
    TECH_LEAD: 'Керівник',
    DATE_OF_ACCEPTING: 'Дата прийняття',
    ACCEPTED_PERSON: 'Автор прийняття',
    DATE_OF_ELIMINATION: 'Дата усунення',
    ELIMINATED: 'Усунено',
    DATE_OF_START_EXPLOITATION: 'Дата початку експлуатації',
    ACCEPTED_EXPLOITATION_PERSON: 'Прийнята особа для експлуатації',
    MOVE_TO: 'Перемістити до',
    COMMENTS: 'Коментарі',
};
