// Table column labels for use in forms and tables
export const TABLE_COLUMNS = {
  DEFECT_STATE: 'Стан дефекту',
  NUMBER: 'Номер',
  SUBSTATION_REGION: 'РЕМ',
  CREATED_AT: 'Дата реєстрації',
  OBJECT: "Тип об'єкту",
  OBJECT_EDIT: 'Об’єкт',
  SUBSTATION: 'Об’єкт',
  SUBSTATION_EDIT: 'Підстанція',
  PLACE_OF_DEFECT: 'Місце дефекту',
  CONNECTION: 'Приєднання',
  ESSENCE_OF_DEFECT: 'Суть дефекту',
  AUTHOR: 'Автор повідомлення',
  TECH_LEAD: 'Технічний керівник',
  RESPONSIBLE_FOR_ELIMINATION: 'Відповідальний за усунення',
  TIME_OF_ELIMINATION: 'Термін усунення',
  DATE_OF_ACCEPTING: 'Дата прийняття до виконання',
  ACCEPTED_PERSON: 'Прийняв до виконання',
  DATE_OF_ELIMINATION: 'Дата усунення',
  ELIMINATED: 'Усунув',
  DATE_OF_START_EXPLOITATION: 'Дата прийняття в експлуатацію',
  ACCEPTED_EXPLOITATION_PERSON: 'Прийняв в експлуатацію',
  MOVE_TO: 'Перемістити до',
  COMMENTS: 'Коментарі',
};

export const TABLE_ITEM_CONDITIONS = {
  'Протермінований': 'red',
  'Прийнятий в експлуатацію': 'green',
  'Переміщений': 'yellow',
};

export const SORT_OPTIONS = [
  { value: 'Condition', label: 'Стан дефекту' },
  { value: 'Order', label: 'Номер' },
  { value: 'DateOfRegistration', label: 'Дата реєстрації' },
  { value: 'ObjectType', label: "Тип об'єкту" },
  { value: 'Place', label: 'Місце дефекту' },
  { value: 'Connection', label: 'Приєднання' },
  { value: 'Description', label: 'Суть дефекту' },
  { value: 'MessageAuthor', label: 'Автор повідомлення' },
  { value: 'Responsible', label: 'Відповідальний за усунення' },
  { value: 'CompletionTerm', label: 'Термін усунення' },
  { value: 'TechnicalManager', label: 'Технічний керівник' },
  { value: 'DateOfAcception', label: 'Дата прийняття' },
  { value: 'AcceptionAuthor', label: 'Прийняв до виконання' },
  { value: 'DateOfCompletion', label: 'Дата усунення' },
  { value: 'ConfirmationAuthor', label: 'Прийняв в експлуатацію' },
  { value: 'DateOfConfirmation', label: 'Дата прийняття в експлуатацію' },
  { value: 'Substation', label: 'Підстанція' },
];

export const INITIAL_ROW_DATA = {
  id: null,
  condition: '',
  substation: '',
  order: null,
  substationRegion: '',
  substationRegionId: '',
  registrationDate: '',
  objectType: '',
  objectNumber: null,
  place: '',
  connection: '',
  description: '',
  messageAuthor: {
    id: null,
    name: '',
    login: '',
    rank: '',
  },
  responsible: {
    id: null,
    name: '',
    login: '',
    rank: '',
  },
  completionTerm: '',
  technicalManager: {
    id: null,
    name: '',
    login: '',
    rank: '',
  },
  acceptionDate: '',
  acceptedBy: {
    id: null,
    name: '',
    login: '',
    rank: '',
  },
  completionDate: '',
  completedBy: {
    id: null,
    name: '',
    login: '',
    rank: '',
  },
  confirmedBy: {
    id: null,
    name: '',
    login: '',
    rank: '',
  },
  confirmationDate: '',
};